spring:
  application:
    name: yugram
  datasource:
    url: jdbc:postgresql://${YUGRAM_DB_HOST:localhost}:${YUGRAM_DB_PORT:5432}/${YUGRAM_DB_NAME:yugram}
    username: ${YUGRAM_DB_USER:yugram}
    password: ${YUGRAM_DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  telegram:
    client:
      api-id: ${TG_API_ID:}
      api-hash: ${TG_API_HASH:}
      application-version: 1.0
      database-directory: database
      device-model: macOS
      enable-storage-optimizer: true
      log-file: tdlib.log
      log-file-max-size: 104857600
      log-verbosity-level: 0
      system-language-code: en
      use-message-database: true
      use-secret-chats: true
      phone-number: ${TG_PHONE_NUMBER:}
      password: ${TG_PASSWORD:}

logging:
  level:
    root: INFO
    live.yurii.yugram: DEBUG